Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -4,7 +4,7 @@ workflows:
     environment:
       flutter: stable
       groups:
-        - web_deploy  # Reference the created environment variable group
+        - repo_credentials  # Reference the created environment variable group
     scripts:
       - name: Install dependencies
         script: flutter pub get
@@ -20,12 +20,18 @@ workflows:
           fi
           ls -la build/web
 
-      - name: Configure Git
-        script: |
-          git config --global user.name "$GIT_USER_NAME"
-          git config --global user.email "$GIT_USER_EMAIL"
-          git config --global credential.helper 'cache --timeout=3600'
-          echo "https://${GITHUB_TOKEN}:@github.com" > ~/.git-credentials
+    - name: Push git tags
+      script: | 
+        #!/usr/bin/env bash
+        set -e # exit on first failed command
+        set -x # print all executed commands to the log
+
+        if [ "$CM_BUILD_STEP_STATUS" = "success" ]
+        then
+          new_version=v1.0.$BUILD_NUMBER
+          git tag $new_version
+          git push "https://your-username:$APP_PASSWORD@your-git-service.com/your-repo.git" --tags
+        fi
 
       - name: Checkout web branch
         script: |
