Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -20,18 +20,18 @@ workflows:
           fi
           ls -la build/web
 
-    - name: Push git tags
-      script: | 
-        #!/usr/bin/env bash
-        set -e # exit on first failed command
-        set -x # print all executed commands to the log
-
-        if [ "$CM_BUILD_STEP_STATUS" = "success" ]
-        then
-          new_version=v1.0.$BUILD_NUMBER
-          git tag $new_version
-          git push "https://your-username:$APP_PASSWORD@your-git-service.com/your-repo.git" --tags
-        fi
+      - name: Push git tags
+        script: | 
+          #!/usr/bin/env bash
+          set -e # exit on first failed command
+          set -x # print all executed commands to the log
+  
+          if [ "$CM_BUILD_STEP_STATUS" = "success" ]
+          then
+            new_version=v1.0.$BUILD_NUMBER
+            git tag $new_version
+            git push "https://your-username:$APP_PASSWORD@your-git-service.com/your-repo.git" --tags
+          fi
 
       - name: Checkout web branch
         script: |
